### Richiesta per TEST KO 1
POST http://{{host}}:{{port}}/LDO/compose/
Content-Type: application/json

< ../test_generator/KO/Test1/test.json
>> ./RESPONSE/KO/test1.xml

> {%
client.test("Request executed successfully", function() {
  client.global.set("error_test_regex", /ERROR/g);
  client.assert(response.status === 200, "Response status is not 200");
});

client.test("No Error Found", function() {
    const regex = client.global.get("error_test_regex");
    if(response.body.match(regex) != null) {
        client.log("Found " + (response.body.match(regex).length/3).toString() + " errors BLOCK");
    }
    client.assert(response.body.match(regex) == null, "Found some ERROR");
});
%}

### Richiesta per TEST KO 2
POST http://{{host}}:{{port}}/LDO/compose/
Content-Type: application/json

< ../test_generator/KO/Test2/test.json
>> ./RESPONSE/KO/test2.xml

> {%
client.test("Request executed successfully", function() {
  client.global.set("error_test_regex", /ERROR/g);
  client.assert(response.status === 200, "Response status is not 200");
});

client.test("No Error Found", function() {
    const regex = client.global.get("error_test_regex");
    if(response.body.match(regex) != null) {
        client.log("Found " + (response.body.match(regex).length/3).toString() + " errors BLOCK");
    }
    client.assert(response.body.match(regex) == null, "Found some ERROR");
});
%}

### Richiesta per TEST KO 3
POST http://{{host}}:{{port}}/LDO/compose/
Content-Type: application/json

< ../test_generator/KO/Test3/test.json
>> ./RESPONSE/KO/test3.xml

> {%
client.test("Request executed successfully", function() {
  client.global.set("error_test_regex", /ERROR/g);
  client.assert(response.status === 200, "Response status is not 200");
});

client.test("No Error Found", function() {
    const regex = client.global.get("error_test_regex");
    if(response.body.match(regex) != null) {
        client.log("Found " + (response.body.match(regex).length/3).toString() + " errors BLOCK");
    }
    client.assert(response.body.match(regex) == null, "Found some ERROR");
});
%}

### Richiesta per TEST KO 4
POST http://{{host}}:{{port}}/LDO/compose/
Content-Type: application/json

< ../test_generator/KO/Test4/test.json
>> ./RESPONSE/KO/test4.xml

> {%
client.test("Request executed successfully", function() {
  client.global.set("error_test_regex", /ERROR/g);
  client.assert(response.status === 200, "Response status is not 200");
});

client.test("No Error Found", function() {
    const regex = client.global.get("error_test_regex");
    if(response.body.match(regex) != null) {
        client.log("Found " + (response.body.match(regex).length/3).toString() + " errors BLOCK");
    }
    client.assert(response.body.match(regex) == null, "Found some ERROR");
});
%}

### Richiesta per TEST KO 5
POST http://{{host}}:{{port}}/LDO/compose/
Content-Type: application/json

< ../test_generator/KO/Test5/test.json
>> ./RESPONSE/KO/test5.xml

> {%
client.test("Request executed successfully", function() {
  client.global.set("error_test_regex", /ERROR/g);
  client.assert(response.status === 200, "Response status is not 200");
});

client.test("No Error Found", function() {
    const regex = client.global.get("error_test_regex");
    if(response.body.match(regex) != null) {
        client.log("Found " + (response.body.match(regex).length/3).toString() + " errors BLOCK");
    }
    client.assert(response.body.match(regex) == null, "Found some ERROR");
});
%}

### Richiesta per TEST KO 6
POST http://{{host}}:{{port}}/LDO/compose/
Content-Type: application/json

< ../test_generator/KO/Test6/test.json
>> ./RESPONSE/KO/test6.xml

> {%
client.test("Request executed successfully", function() {
  client.global.set("error_test_regex", /ERROR/g);
  client.assert(response.status === 200, "Response status is not 200");
});

client.test("No Error Found", function() {
    const regex = client.global.get("error_test_regex");
    if(response.body.match(regex) != null) {
        client.log("Found " + (response.body.match(regex).length/3).toString() + " errors BLOCK");
    }
    client.assert(response.body.match(regex) == null, "Found some ERROR");
});
%}